dnl # SPDX-License-Identifier: CDDL-1.0
dnl #
dnl # Default ZFS user configuration
dnl #
AC_DEFUN([ZFS_AC_CONFIG_USER], [
	ZFS_AC_CONFIG_USER_GETTEXT
	ZFS_AC_CONFIG_USER_LARGEFILE
	ZFS_AC_CONFIG_USER_MOUNT_HELPER
	ZFS_AC_CONFIG_USER_SYSVINIT
	ZFS_AC_CONFIG_USER_DRACUT
	AM_COND_IF([BUILD_FREEBSD], [
		PKG_INSTALLDIR(['${prefix}/libdata/pkgconfig'])], [
		PKG_INSTALLDIR
	])
	ZFS_AC_CONFIG_USER_ZLIB
	AM_COND_IF([BUILD_LINUX], [
		ZFS_AC_CONFIG_USER_UDEV
		ZFS_AC_CONFIG_USER_SYSTEMD
		ZFS_AC_CONFIG_USER_LIBUDEV
		ZFS_AC_CONFIG_USER_LIBUUID
		ZFS_AC_CONFIG_USER_LIBBLKID
		ZFS_AC_CONFIG_USER_STATX
		ZFS_AC_CONFIG_USER_MOUNT_SETATTR
	])
	ZFS_AC_CONFIG_USER_LIBTIRPC
	ZFS_AC_CONFIG_USER_LIBCRYPTO
	ZFS_AC_CONFIG_USER_LIBAIO
	ZFS_AC_CONFIG_USER_LIBATOMIC
	ZFS_AC_CONFIG_USER_LIBFETCH
	ZFS_AC_CONFIG_USER_AIO_H
	ZFS_AC_CONFIG_USER_CLOCK_GETTIME
	ZFS_AC_CONFIG_USER_EXPLICIT_MEMSET
	ZFS_AC_CONFIG_USER_PTHREAD_SETNAME_NP
	ZFS_AC_CONFIG_USER_XDR_BYTESREC
	ZFS_AC_CONFIG_USER_SEEK_HOLE
	ZFS_AC_CONFIG_USER_UF_READONLY
	ZFS_AC_CONFIG_USER_STRUCT_STATFS
	ZFS_AC_CONFIG_USER_PAM
	ZFS_AC_CONFIG_USER_BACKTRACE
	ZFS_AC_CONFIG_USER_LIBUNWIND
	ZFS_AC_CONFIG_USER_RUNSTATEDIR
	ZFS_AC_CONFIG_USER_MAKEDEV_IN_SYSMACROS
	ZFS_AC_CONFIG_USER_MAKEDEV_IN_MKDEV
	ZFS_AC_CONFIG_USER_ZFSEXEC

	AC_CHECK_FUNCS([execvpe issetugid mlockall strlcat strlcpy gettid])
	AC_CHECK_FUNCS([copy_file_range pthread_setconcurrency])
	AM_CONDITIONAL([HAVE_COPY_FILE_RANGE],
	    [test "x$ac_cv_func_copy_file_range" = xyes])
	AC_CHECK_FUNCS([preadv2 pwritev2])

	AC_SUBST(RM)
])
